version: '3'

services:
  am-judicial-booking-service:
    build:
      context: .
    image: hmcts/am-judicial-booking-service
    container_name: am-judicial-booking-service
    environment:
      - JUDICIAL_BOOKING_SERVICE_POSTGRES_HOST=am-judicial-booking-database
      - JUDICIAL_BOOKING_SERVICE_POSTGRES_DATABASE=judicial_booking
      - JUDICIAL_BOOKING_SERVICE_POSTGRES_PORT=5432
      - JUDICIAL_BOOKING_SERVICE_POSTGRES_USER=am
      - JUDICIAL_BOOKING_SERVICE_POSTGRES_PASS=am
      - AM_JUDICIAL_BOOKING_DB_OPTIONS
      - AM_JUDICIAL_BOOKING_SERVICE_SECRET
      - LD_SDK_KEY
      - JUDICIAL_BOOKING_IDAM_CLIENT_ID
      - JUDICIAL_BOOKING_IDAM_CLIENT_SECRET
      - JUDICIAL_BOOKING_IDAM_ADMIN_USERID
      - JUDICIAL_BOOKING_IDAM_ADMIN_PASSWORD
      - AM_JUDICIAL_BOOKING_S2S_AUTHORISED_SERVICES
      - IDAM_USER_URL
      - IDAM_S2S_URL
      - AZURE_APPLICATIONINSIGHTS_INSTRUMENTATIONKEY
      - REFORM_SERVICE_NAME=am-judicial-booking-service
      - REFORM_TEAM=am
      - REFORM_ENVIRONMENT=local
    ports:
      - ${SERVER_PORT:-4097}:${SERVER_PORT:-4097}
    depends_on:
      - am-judicial-booking-database
    links:
      - am-judicial-booking-database

  am-judicial-booking-database:
    build:
      context: docker/database
    container_name: am-judicial-booking-database
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      - JUDICIAL_BOOKING_SERVICE_POSTGRES_USER=am
      - JUDICIAL_BOOKING_SERVICE_POSTGRES_PASS=am
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5455:5432
    volumes:
      - am-judicial-booking-database-data:/var/lib/postgresql/am-judicial-booking/data
volumes:
  am-judicial-booking-database-data:
