server:
  port: ${PORT:4097}

management:
  health:
    db:
      enabled: true
    defaults:
      enabled: true
    diskspace:
      enabled: true
  endpoint:
    health:
      enabled: true
      cache:
        time-to-live: 5s
      show-details: "always"
  security:
    enabled: false
  endpoints:
    health:
      sensitive: false
    web:
      base-path: /
      exposure:
        include: 'health'

#If you use a database then uncomment below lines and update db properties accordingly

security:
  anonymousPaths:
    - "/"
    - "/health"
    - "/health/liveness"
    - "/actuator/**"
    - "/loggers/**"
    - "/swagger-ui.html"
    - "/swagger-resources/**"
    - "/v2/api-docs"
    - "/webjars/springfox-swagger-ui/**"
    - "/search/**"
    - "/csrf"
    - "/error"
    - "/favicon.ico"
  authorisedRoles:
  authorisedServices: ${AM_JUDICIAL_BOOKING_S2S_AUTHORISED_SERVICES:ccd_gw,am_judicial-booking_service}

spring:
  application:
    name: Judicial Booking Service
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    log_statement: all
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    enabled: ${ENABLE_DB_MIGRATE:true}
    change-log: classpath:/db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://${AM_JUDICIAL_BOOKING_DB_HOST:localhost}:${AM_JUDICIAL_BOOKING_DB_PORT:5455}/${AM_JUDICIAL_BOOKING_DB_NAME:judicial_booking}${AM_JUDICIAL_BOOKING_DB_OPTIONS:?stringtype=unspecified}
    username: ${AM_JUDICIAL_BOOKING_DB_USERNAME:am}
    password: ${AM_JUDICIAL_BOOKING_DB_PASSWORD:am}

### dependency configuration
auth.provider.service.client.baseUrl: ${IDAM_S2S_URL:http://localhost:4502}
idam:
  s2s-auth:
    # AAAAAAAAAAAAAAAA
    totp_secret: ${AM_JUDICIAL_BOOKING_SERVICE_SECRET:AAAAAAAAAAAAAAAA}
    microservice: am_judicial_booking_service
    url: ${IDAM_S2S_URL:http://localhost:4502}

auth.idam.client.baseUrl: ${IDAM_USER_URL:http://localhost:5000}
testS2S:
  api:
    url: "/testS2SAuthorization"
integrationTest:
  api:
    url: "/"

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
      datastoreclient:
        url: ${CCD_DATA_STORE_URL:http://localhost:4452}

swaggerUrl: "${AM_JUDICIAL_BOOKING_SWAGGER_AM_URL:localhost:4097}"
judicialBookingUrl: ${TEST_URL:http://localhost:4097}
