#!/usr/bin/env bash

set -e

if [ -z "$JUDICIAL_BOOKING_SERVICE_POSTGRES_USER" ] || [ -z "$JUDICIAL_BOOKING_SERVICE_POSTGRES_PASS" ]; then
  echo "ERROR: Missing environment variable. Set value for both 'JUDICIAL_BOOKING_SERVICE_POSTGRES_USER' and 'JUDICIAL_BOOKING_SERVICE_POSTGRES_PASS'."
  exit 1
fi

# Create role and database
psql -v ON_ERROR_STOP=1 --username postgres --set USERNAME=$JUDICIAL_BOOKING_SERVICE_POSTGRES_USER --set PASSWORD=$JUDICIAL_BOOKING_SERVICE_POSTGRES_PASS <<-EOSQL
  CREATE USER :USERNAME WITH PASSWORD ':PASSWORD';
  CREATE DATABASE judicial_booking
    WITH OWNER = :USERNAME
    ENCODING = 'UTF-8'
    CONNECTION LIMIT = -1;
  ALTER SCHEMA public OWNER TO :USERNAME;

EOSQL
