java:
  image: 'hmctspublic.azurecr.io/am/judicial-booking-service:latest'
  ingressHost: am-judicial-booking-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  applicationPort: 4097
  aadIdentityName: am
  keyVaults:
    am:
      secrets:
        - am-judicial-booking-service-s2s-secret
        - judicial-booking-service-POSTGRES-PASS
        - AppInsightsInstrumentationKey
        - judicial-booking-service-IDAM-CLIENT-SECRET
        - judicial-booking-service-IDAM-ADMIN-SECRET
        - role-assignment-service-LD-SDK-KEY
  environment:
    IDAM_S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    IDAM_USER_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    AM_JUDICIAL_BOOKING_S2S_AUTHORISED_SERVICES: am_judicial_booking_service
    JUDICIAL_BOOKING_SERVICE_POSTGRES_PORT: 5432
    JUDICIAL_BOOKING_SERVICE_POSTGRES_DATABASE: judicial_booking
    JUDICIAL_BOOKING_SERVICE_POSTGRES_HOST: am-judicial-booking-service-postgres-db-{{ .Values.global.environment }}.postgres.database.azure.com
    JUDICIAL_BOOKING_SERVICE_POSTGRES_USER: am@am-judicial-booking-service-postgres-db-{{ .Values.global.environment }}
    OIDC_ISSUER_URL: https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts
    OPEN_ID_API_BASE_URI: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/o
    LAUNCH_DARKLY_ENV: "{{ .Values.global.environment }}"
    MICROSERVICE_NAME: am_judicial_booking_service
    JUDICIAL_BOOKING_IDAM_ADMIN_USERID: ras-validation-system@hmcts.net