java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    am:
      secrets:
        - name: am-judicial-booking-service-s2s-secret
          alias: AM_JUDICIAL_BOOKING_SERVICE_SECRET
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: judicial-booking-service-IDAM-CLIENT-SECRET
          alias: JUDICIAL_BOOKING_IDAM_CLIENT_SECRET
        - name: judicial-booking-service-IDAM-ADMIN-SECRET
          alias: JUDICIAL_BOOKING_IDAM_ADMIN_PASSWORD
        - name: role-assignment-service-LD-SDK-KEY
          alias: LD_SDK_KEY

  environment:
    JUDICIAL_BOOKING_SERVICE_POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    JUDICIAL_BOOKING_SERVICE_POSTGRES_DATABASE: "{{ .Values.postgresql.auth.database}}"
    JUDICIAL_BOOKING_SERVICE_POSTGRES_USER: "{{ .Values.postgresql.auth.username}}"
    JUDICIAL_BOOKING_SERVICE_POSTGRES_PASS: "{{ .Values.postgresql.auth.password}}"
    JUDICIAL_BOOKING_SERVICE_POSTGRES_PORT: "{{ .Values.postgresql.postgresqlPort}}"
    JUDICIAL_BOOKING_SERVICE_DB_OPTIONS: "?stringtype=unspecified"
    IDAM_S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    LAUNCH_DARKLY_ENV: pr
  postgresql:
    enabled: true
    postgresqlUsername: am
    postgresqlPassword: am
    postgresqlDatabase: judicial_booking
    postgresqlPort: 5432
